server:
    port: ${PORT:8081}

spring:
    application:
        name: clientes-app
    datasource:
        url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/your_database_name}
        username: ${DATASOURCE_USERNAME:your_username}
        password: ${DATASOURCE_PASSWORD:your_password}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update  # Use 'update' to automatically update schema (create or update tables)
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC  # Set JDBC time zone to UTC (optional, adjust as needed)
        show-sql: false  # Enable SQL logging (optional, for debugging)
        generate-ddl: false  # Generate DDL from entity models (optional, for schema creation)
        open-in-view: false  # Disable Open Session in View (OSIV) to prevent lazy loading issues

